# Generated by Django 5.2.16 on 2026-07-26 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostel_name', models.CharField(max_length=100, unique=True)),
                ('hostel_type', models.CharField(choices=[('Boys', 'Boys'), ('Girls', 'Girls')], max_length=10)),
                ('address', models.TextField()),
                ('total_rooms', models.PositiveIntegerField()),
                ('hostel_image', models.ImageField(blank=True, null=True, upload_to='hostels/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
