# Generated by Django 5.2.15 on 2026-06-23 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.CharField(default='Normal', max_length=20),
            preserve_default=False,
        ),
    ]
