# Generated by Django 5.2.15 on 2026-06-23 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0002_room_room_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(default='Double', max_length=20),
        ),
    ]
