# Generated by Django 5.2.15 on 2026-06-27 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hostels', '0003_alter_room_room_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hosteller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(default='Hostel Manager', max_length=100)),
                ('joined_date', models.DateField(auto_now_add=True)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostellers', to='hostels.hostel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hosteller_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
